name: "Tests & examples on macOS"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Tests & examples on macOS
    runs-on: macos-13
    if:  ${{ github.event_name == 'pull_request' || github.repository == 'PalamaraLab/arg-needle-lib' }}

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v5

      - name: install system packages
        run: |
          brew install boost eigen hdf5

      - name: make build directory
        run: mkdir build_dir

      - name: cmake configure

        run: cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++ -DCMAKE_C_COMPILER=$(brew --prefix llvm@15)/bin/clang
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2
        working-directory: build_dir

      - name: cmake test
        run: ctest -j2 --output-on-failure
        working-directory: build_dir

      - name: run example arg
        run: ./example/example_arg
        working-directory: build_dir

      - name: run example mutation
        run: ./example/example_mutation
        working-directory: build_dir

      - name: run example node
        run: ./example/example_node
        working-directory: build_dir

      - name: run example visit
        run: ./example/example_visit
        working-directory: build_dir

      - name: run example sumstats
        run: ./example/example_sumstats
        working-directory: build_dir
